[package]
name = "SuiVerseCertificate"
version = "1.0.0"
authors = ["Jinu Ahn"]
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
SuiVerseCore = { local = "../suiverse-core" }
SuiVerseContent = { local = "../suiverse-content" }
SuiVerseEconomics = { local = "../suiverse-economics" }

[addresses]
suiverse_core = "0x711a615a0603193f81f2ca50db96bc2231c6fb070a58ee95917347a410473faf"
suiverse_content = "0xe85e9cccdd08468abc23c1e3411112f9b24d1d2d146d5a851dd7cc3fde3326d7"
suiverse_economics = "0x07324a2f816fd4ef9d45a03b0d24768d2b03bcc70047b8133e063fc4828ac393"
suiverse_certificate = "0x9235fadc670ce4b8203d4d9976febbf56f93a5e1413205587c4bea912192c327"

[dev-dependencies]